Section "InputClass"
    Identifier "14:13330:BTK1_BT5.0_Keyboard"
    MatchIsKeyboard "on"

    Option "XkbModel" "btk1_bt5"
    Option "XkbLayout" "us"
    Option "XkbOptions" "altwin:swap_lalt_lwin"
EndSection
