# run files dumped with PROTON_DUMP_DEBUG_COMMANDS=1

_game FOLDER EXE ID ENV="" START_PREFIX="GAMEMODERUNEXEC=pvkrun gamemoderun" PREFIX="/mnt/LENOVO/SteamLibrary/steamapps" PROTON="/mnt/LENOVO/SteamLibrary/steamapps/common/Proton 5.13":
	#!/bin/bash

	cd "{{PREFIX}}/common/{{FOLDER}}"
	DEF_CMD=("{{PREFIX}}/common/{{FOLDER}}/{{EXE}}")
	PATH="{{PROTON}}/dist/bin/:/usr/bin:/bin" \
	TERM="xterm" \
	WINEDEBUG="-all" \
	WINEDLLPATH="{{PROTON}}/dist/lib64//wine:{{PROTON}}/dist/lib//wine" \
	LD_LIBRARY_PATH="{{PROTON}}/dist/lib64/:{{PROTON}}/dist/lib/:/overrides/lib/x86_64-linux-gnu:/overrides/lib/i386-linux-gnu" \
	WINEPREFIX="{{PREFIX}}/compatdata/{{ID}}/pfx/" \
	WINEESYNC="1" \
	WINEFSYNC="1" \
	SteamGameId="{{ID}}" \
	SteamAppId="{{ID}}" \
	WINEDLLOVERRIDES="steam.exe=b;dotnetfx35.exe=b;mfplay=n;dxvk_config=n;d3d11=n;d3d10=n;d3d10core=n;d3d10_1=n;d3d9=n" \
	STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/heyrict/.local/share/Steam" \
	WINE_LARGE_ADDRESS_AWARE="1" \
	GST_PLUGIN_SYSTEM_PATH_1_0="{{PROTON}}/dist/lib64/gstreamer-1.0:{{PROTON}}/dist/lib/gstreamer-1.0" \
	WINE_GST_REGISTRY_DIR="{{PREFIX}}/compatdata/{{ID}}/gstreamer-1.0/" \
	MEDIACONV_AUDIO_DUMP_FILE="{{PREFIX}}/shadercache/{{ID}}/fozmediav1/audio.foz" \
	MEDIACONV_AUDIO_TRANSCODED_FILE="{{PREFIX}}/shadercache/{{ID}}/swarm/transcoded_audio.foz" \
	MEDIACONV_VIDEO_DUMP_FILE="{{PREFIX}}/shadercache/{{ID}}/fozmediav1/video.foz" \
	MEDIACONV_VIDEO_TRANSCODED_FILE="{{PREFIX}}/shadercache/{{ID}}/swarm/transcoded_video.foz" \
	{{ENV}} {{START_PREFIX}} "{{PROTON}}/dist/bin/wine" steam.exe "${@:-${DEF_CMD[@]}}"

tales_of_berseria:
	just _game "Tales of Berseria" "Tales of Berseria.exe" "429660" "PULSE_LATENCY_MSEC=30"

rabi_ribi:
	just _game "Rabi-Ribi" "rabiribi.exe" "400910" "WINEESYNC=0" ""

atelier_firis:
	just _game "Atelier Firis The Alchemist and the Mysterious Journey" "A18.exe" "527290"

atelier_firis_config:
	just _game "Atelier Firis The Alchemist and the Mysterious Journey" "A18Config.exe" "527290"

disgaea:
	just _game "Disgaea PC" "dis1_st.exe" 405900 "" "GAMEMODERUNEXEC=pvkrun gamemoderun" "/home/heyrict/.local/share/Steam/steamapps"

atelier_ayesha:
	just _game "Atelier Ayesha DX" "Atelier_AyeshaLauncher.exe" 1152300 "" "LC_ALL=ja_JP.utf-8 pvkrun" "/home/heyrict/.local/share/Steam/steamapps"
