#!/usr/bin/env bash

EXNOTIFY_SEND=dunstify
AUDIO_STEPS=3
#OPTIMAL_AUDIO=20

type -p wpctl &>/dev/null || exec "$EXNOTIFY_SEND" -u low -r 15 'Install wpctl!'

notify()
{
    VOLUME=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2 * 100)}')
    MUTE=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '/MUTED/ {print "true"} !/MUTED/ {print "false"}')
    if [ "$MUTE" = "true" ] || [ "$VOLUME" -eq 0 ]; then
        #icon='notification-audio-volume-muted'
        icon='audio-volume-muted-symbolic'
    elif [ "$VOLUME" -lt 30 ]; then
        #icon='notification-audio-volume-low'
        icon='audio-volume-low-symbolic'
    elif [ "$VOLUME" -lt 70 ]; then
        #icon='notification-audio-volume-medium'
        icon='audio-volume-medium-symbolic'
    else
        #icon='notification-audio-volume-high'
        icon='audio-volume-high-symbolic'
    fi
    exec "$EXNOTIFY_SEND" -r 123 -t 700 -i "$icon" "$VOLUME " -h "int:value:${VOLUME}"
}

case ${1} in
    up)   wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ "${AUDIO_STEPS:-5}%+";;
    down) wpctl set-volume @DEFAULT_AUDIO_SINK@ "${AUDIO_STEPS:-5}%-";;
    mute) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle;;
esac

notify

exit ${?}
