ROOT := "/home/heyrict/.wine32"
HOME := "/home/heyrict/.wine32/drive_c/users/heyrict"

run FILE:
	cd "$(dirname '{{FILE}}')" && LC_ALL=ja_JP.UTF-8 LANG=ja_JP.UTF-8 WINEARCH=win32 WINEPREFIX="{{ROOT}}" wine "$(basename '{{FILE}}')"

winetricks +ARGS="":
	LC_ALL=ja_JP.UTF-8 LANG=ja_JP.UTF-8 WINEARCH=win32 WINEPREFIX="{{ROOT}}" winetricks {{ARGS}}

kill:
	LC_ALL=ja_JP.UTF-8 LANG=ja_JP.UTF-8 WINEARCH=win32 WINEPREFIX="{{ROOT}}" wineserver -k

reverse:
	just run "{{HOME}}/Games/era/eraReverse1214/Emuera1824+v1.exe"

syokusyu:
	just run "{{HOME}}/Games/era/syokusyu1150/Emuera1824+v10.exe"

theworld:
	just run "{{HOME}}/Games/era/eraTW4891/Emuera.exe"

k:
	just run "{{HOME}}/Games/era/eratohoK1293/Emuera1824+v9.exe"

rsyokusyu:
	just run "{{HOME}}/Games/era/rsyokusyuV337/Emuera1823beta003.exe"

ymaem:
	just run "{{HOME}}/Games/era/eraYMAEM4269/Emuera1824+v13.exe"

awt:
	just run "{{HOME}}/Games/era/eraAWT1004/Emuera1824+v5.exe"

akumaMaid:
	just run "{{HOME}}/Games/era/eraAkumaMaid 2022_08_23/Emuera1824+v15.exe"

t:
	just run "{{HOME}}/Games/era/eratohoT3300/Emuera1824.exe"

as:
	just run "{{HOME}}/Games/era/eraAS_0.665/Emuera1824+v5.exe"
