ROOT := "/home/heyrict/legendary/pfx"
HOME := ROOT + "/drive_c/users/heyrict"
#PROTON := "/home/heyrict/.local/share/Steam/steamapps/common/Proton 5.13"
#PROTON_WINE64 := PROTON + "/dist/bin/wine64"
PROTON := "/home/heyrict/.local/share/Steam/compatibilitytools.d/GE-Proton7-25"
PROTON_WINE64 := PROTON + "/files/bin/wine64"
PROTON_ENV := "DXVK_ASYNC=1 WINE_FULLSCREEN_FSR=1 WINE_FULLSCREEN_FSR_MODE=performance"

sync:
	legendary sync-saves

kill:
	{{PROTON}}/files/bin/wineserver -k

kill9:
	{{PROTON}}/files/bin/wineserver -k9

run FILE:
	cd "$(dirname '{{FILE}}')" && env WINEPREFIX="{{ROOT}}" "{{PROTON_WINE64}}" "$(basename '{{FILE}}')"

sonic_mania +OPTIONS="":
	{{PROTON_ENV}} legendary launch {{OPTIONS}} 818447bb519b46d48d365d5753362796
