ROOT := "/home/heyrict/legendary/pfx"
HOME := ROOT + "/drive_c/users/heyrict"
PROTON_VERSION := "current"
PROTON := "/home/heyrict/WineGE/" + PROTON_VERSION
PROTON_WINE64 := PROTON + "/bin/wine64"

FSR_MODE := "performance"
PROTON_ENV := "DXVK_ASYNC=1 WINE_FULLSCREEN_FSR=1 WINE_FULLSCREEN_FSR_MODE=" + FSR_MODE

sync:
	legendary sync-saves

kill:
	{{PROTON}}/bin/wineserver -k

kill9:
	{{PROTON}}/bin/wineserver -k9

run FILE:
	cd "$(dirname '{{FILE}}')" && env WINEPREFIX="{{ROOT}}" "{{PROTON_WINE64}}" "$(basename '{{FILE}}')"

sonic_mania +OPTIONS="":
	{{PROTON_ENV}} legendary launch {{OPTIONS}} 818447bb519b46d48d365d5753362796

overcooked +OPTIONS="":
	{{PROTON_ENV}} legendary launch {{OPTIONS}} Sage
