ROOT := "/home/heyrict/legendary/pfx"
HOME := ROOT + "/drive_c/users/heyrict"
PROTON := "/home/heyrict/.local/share/Steam/steamapps/common/Proton 5.13"
PROTON_WINE64 := PROTON + "/dist/bin/wine64"

sync:
	legendary sync-saves

bridge_constructor_twd:
	#legendary launch --wine-prefix="{{ROOT}}" 998af0ab527c493baefb8049250c9a0e
	legendary launch 998af0ab527c493baefb8049250c9a0e
