---
runtime:
  threads: ~
manifest:
  url: "https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml"
language: en-US
theme: dark
roots:
  - store: steam
    path: ~/.steam/steam
  - store: otherWine
    path: ~/.wine
  - store: otherWine
    path: ~/legendary/pfx
  - store: otherWine
    path: /run/media/heyrict/wd23e/heyrict/wine
  - store: otherWine
    path: /run/media/heyrict/zt23b/heyrict/wine
  - store: steam
    path: /run/media/heyrict/wd22b/heyrict/steam/
  - store: steam
    path: /run/media/heyrict/zt23b/heyrict/Steam/
  - store: steam
    path: /run/media/heyrict/SG20E/SteamLibrary
redirects: []
backup:
  path: /home/heyrict/Sync/backup/ludusavi
  ignoredGames:
    - "AI: The Somnium Files"
    - Autonauts
    - "Bridge Constructor: The Walking Dead"
    - Dolphin
    - Epistory - Typing Chronicles
    - Lego Bricktales
    - Lego The Lord of the Rings
    - "Mary Skelter: Nightmares"
    - Model Builder
    - "Monster Hunter Stories 2: Wings of Ruin"
    - My Time at Portia
    - RPG Fighter League
    - RetroArch
    - Stranded Deep
    - "Sword Art Online: Lost Song"
    - Tales of Berseria
    - Tales of the Neon Sea
    - "The Legend of Heroes: Trails of Cold Steel II"
    - This War of Mine
    - Tomb Raider (2013)
    - "Utawarerumono: Prelude to the Fallen"
    - Worms Clan Wars
  filter:
    excludeStoreScreenshots: true
    cloud:
      exclude: false
      epic: false
      gog: false
      origin: false
      steam: false
      uplay: false
    ignoredPaths: []
    ignoredRegistry: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: name
    reversed: false
  retention:
    full: 1
    differential: 0
  format:
    chosen: simple
    zip:
      compression: deflate
    compression:
      deflate:
        level: 6
      bzip2:
        level: 6
      zstd:
        level: 10
restore:
  path: /home/heyrict/Sync/backup/ludusavi
  ignoredGames: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: name
    reversed: false
scan:
  showDeselectedGames: true
  showUnchangedGames: true
  showUnscannedGames: true
cloud:
  remote: ~
  path: ludusavi-backup
  synchronize: true
apps:
  rclone:
    path: /usr/bin/rclone
    arguments: "--fast-list --ignore-checksum"
customGames:
  - name: "Monochrome Mobius: Rights and Wrongs Forgotten"
    files:
      - /home/heyrict/.local/share/Steam/steamapps/compatdata/1962430/pfx/drive_c/users/steamuser/Documents/AQUAPLUS/MonochromeMobius Rights and Wrongs Forgotten
    registry: []
  - name: Nekomimi Sweet Housemates
    files:
      - /home/heyrict/.local/share/Steam/steamapps/compatdata/1789650/pfx/drive_c/users/steamuser/AppData/LocalLow/AnimalHerb/Nekomimi Sweet Housemates
    registry: []
  - name: Atelier Shallie DX
    files:
      - /home/heyrict/.local/share/Steam/steamapps/compatdata/1152320/pfx/drive_c/users/steamuser/My Documents/KoeiTecmo/Atelier Shallie DX/
    registry: []
