---
manifest:
  url: "https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml"
  etag: "\"b4d7f1b67b9e68b0cce2985472cebc001907a974637f608ebd3da24dd549db8b\""
language: en-US
theme: dark
roots:
  - path: ~/.steam/steam
    store: steam
  - path: ~/.wine
    store: otherWine
  - path: ~/legendary/pfx
    store: otherWine
  - path: /run/media/heyrict/wd23e/heyrict/wine
    store: otherWine
  - path: /run/media/heyrict/zt23b/heyrict/wine
    store: otherWine
  - path: /run/media/heyrict/wd22b/heyrict/steam/
    store: steam
  - path: /run/media/heyrict/zt23b/heyrict/Steam/
    store: steam
  - path: /run/media/heyrict/SG20E/SteamLibrary
    store: steam
backup:
  path: /home/heyrict/Sync/backup/ludusavi
  ignoredGames:
    - "AI: The Somnium Files"
    - Autonauts
    - "Bridge Constructor: The Walking Dead"
    - Epistory - Typing Chronicles
    - Lego Bricktales
    - Lego The Lord of the Rings
    - "Mary Skelter: Nightmares"
    - Model Builder
    - "Monster Hunter Stories 2: Wings of Ruin"
    - My Time at Portia
    - RPG Fighter League
    - RetroArch
    - Stranded Deep
    - "Sword Art Online: Lost Song"
    - Tales of Berseria
    - Tales of the Neon Sea
    - "The Legend of Heroes: Trails of Cold Steel II"
    - This War of Mine
    - Tomb Raider (2013)
    - "Utawarerumono: Prelude to the Fallen"
    - Worms Clan Wars
  recentGames:
    - A Short Hike
    - "AI: The Somnium Files"
    - Atelier Escha and Logy DX
    - "Atelier Firis: The Alchemist and the Mysterious Journey"
    - "Atelier Sophie: The Alchemist of the Mysterious Book DX"
    - Baba Is You
    - Back to Bed
    - "Bridge Constructor: The Walking Dead"
    - Bullet Girls Phantasia
    - Celeste
    - Chaos;Child
    - Cosmic Express
    - Disgaea PC
    - Epistory - Typing Chronicles
    - "Final Fantasy XII: The Zodiac Age"
    - Gal*Gun Returns
    - Hidden Folks
    - "Hyperdimension Neptunia Re;Birth 2: Sisters Generation"
    - It Takes Two
    - Lego The Lord of the Rings
    - Model Builder
    - "Monster Hunter Stories 2: Wings of Ruin"
    - My Time at Portia
    - Nekomimi Sweet Housemates
    - "Neptunia x Senran Kagura: Ninja Wars"
    - NieR Replicant
    - Orwell
    - Overcooked!
    - Phantom Brave PC
    - RetroArch
    - Rune Factory 5
    - Shining Resonance Refrain
    - Sonic Mania
    - Supraland
    - "Sword Art Online: Lost Song"
    - Tales of Berseria
    - Tales of Zestiria
    - Tales of the Neon Sea
    - "The Legend of Heroes: Trails of Cold Steel II"
    - This War of Mine
    - Tokyo Xanadu eX+
    - Tomb Raider (2013)
    - Unrailed!
    - Untitled Goose Game
    - "Utawarerumono: Prelude to the Fallen"
    - Worms Clan Wars
    - Yakuza Kiwami
    - "Ys VIII: Lacrimosa of DANA"
  merge: true
  filter:
    excludeStoreScreenshots: true
    ignoredPaths: []
    ignoredRegistry: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: name
    reversed: false
  retention:
    full: 1
    differential: 0
  format:
    chosen: simple
    zip:
      compression: deflate
restore:
  path: /home/heyrict/Sync/backup/ludusavi
  ignoredGames: []
  recentGames: []
  redirects: []
  sort:
    key: name
    reversed: false
customGames:
  - name: "Monochrome Mobius: Rights and Wrongs Forgotten"
    files:
      - /home/heyrict/.local/share/Steam/steamapps/compatdata/1962430/pfx/drive_c/users/steamuser/Documents/AQUAPLUS/MonochromeMobius Rights and Wrongs Forgotten
    registry: []
  - name: Nekomimi Sweet Housemates
    files:
      - /home/heyrict/.local/share/Steam/steamapps/compatdata/1789650/pfx/drive_c/users/steamuser/AppData/LocalLow/AnimalHerb/Nekomimi Sweet Housemates
    registry: []
  - name: Atelier Escha and Logy DX
    files:
      - /home/heyrict/.local/share/Steam/steamapps/compatdata/1152310/pfx/drive_c/users/steamuser/Documents/KoeiTecmo/Atelier Escha and Logy DX/
    registry: []
  - name: Atelier Shallie DX
    files:
      - /home/heyrict/.local/share/Steam/steamapps/compatdata/1152320/pfx/drive_c/users/steamuser/My Documents/KoeiTecmo/Atelier Shallie DX/
    registry: []
