# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

# Preferred before program names
"private browsing" = ""
"mooc" = ""

# Brand names
"github" = ""
"gitlab" = ""
"google" = ""
"bing" = ""
"baidu" = ""
"evernote" = ""
"amazon" = ""
"steam" = ""
"appinn" = "懲"
"archlinux" = ""
"arch linux" = ""
"aur" = ""
"ubuntu" = "漢"
"stackoverflow" = ""
"stackexchange" = "﬊"
"digitalocean" = ""
"wiki" = "磌"
"docker" = ""
"paypal" = ""
"wechat" = ""
"coursera" = ""
"linux" = ""

# Specific program names
"feh" = ""
"firefox" = ""
"chrome" = ""
"chromium" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = ""
"calculator" = ""
"transmission" = ""
"aria2" = ""
"rust" = ""
"anki" = ""
"elinks" = ""
"ppsspp" = ""
"pcsx2" = ""
"vim" = ""
"keepass" = ""
"deluge" = "懲"
"calibre" = "龎"
"zotero" = ""
"inkscape" = ""
"gimp" = ""
"python" = ""

# Generic
"tty" = ""
"term" = ""
"log" = ""
"志方あきこ" = ""
"file manager" = ""
"menu" = ""
"videostream" = ""
"mpv" = "ﳜ"
"music" = ""
"disk" = ""
"notebook" = ""
".pdf" = ""
"float" = "缾"
