[colors.primary]
background = "#002b36" # base03
foreground = "#839496" # base0

# Cursor colors
[colors.cursor]
text = "#002b36" # base03
cursor = "#839496" # base0

# Normal colors
[colors.normal]
black = "#073642" # base02
red = "#dc322f" # red
green = "#859900" # green
yellow = "#b58900" # yellow
blue = "#268bd2" # blue
magenta = "#d33682" # magenta
cyan = "#2aa198" # cyan
white = "#eee8d5" # base2

# Bright colors
[colors.bright]
black = "#002b36" # base03
red = "#cb4b16" # orange
green = "#586e75" # base01
yellow = "#657b83" # base00
blue = "#839496" # base0
magenta = "#6c71c4" # violet
cyan = "#93a1a1" # base1
white = "#fdf6e3" # base3

[colors.dim]
black = "#32302f"
blue = "#076678"
cyan = "#427b58"
green = "#79740e"
magenta = "#8f3f71"
red = "#9d0006"
white = "#928374"
yellow = "#b57614"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"
