sync:
	just pull_file /etc/X11/xorg.conf.d
	just pull_file /etc/anacrontab
	just pull_file /etc/apt/apt.conf.d/00aptitude
	just pull_file /etc/bumblebee
	just pull_file /etc/crontab
	just pull_file /etc/davfs2/davfs2.conf
	just pull_file /etc/dictd
	just pull_file /etc/fstab
	just pull_file /etc/hostapd
	just pull_file /etc/hosts
	just pull_file /etc/udhcpd.conf
	just pull_file /etc/vsftpd.conf

pull_file FILE:
	#!/usr/bin/env sh
	d=`dirname "{{FILE}}" | sed "s/^\///"`
	if [ ! -d "$d" ]; then
		mkdir -p "$d"
	fi
	rsync -puir "{{FILE}}" "$d"
