firefox-clean:
	#!/usr/bin/env zsh
	#
	# Clean files from firefox
	#
	# Previous result of `file --mime-type * | cut -d" " -f 2 | sort | uniq -c`:
	#
	# ```
	# 7834 application/gzip
	#  665 application/json
	# 7170 application/octet-stream
	#    1 application/vnd.openxmlformats-officedocument.wordprocessingml.document
	#   15 application/x-dosexec
	#    2 application/zip
	#    1 application/zlib
	#   12 audio/mpeg
	#    1 audio/x-hx-aac-adts
	#    1 audio/x-mp4a-latm
	#    9 font/sfnt
	#  463 image/gif
	# 2310 image/jpeg
	# 2169 image/png
	#  181 image/svg+xml
	#   29 image/vnd.microsoft.icon
	#  315 image/webp
	#    1 image/x-win-bitmap
	#    1 video/mp4
	#    9 video/webm
	# ```
	#
	for f in ./mozilla/firefox/*/cache2/entries/*; do
		_mimetype="$(file --mime-type $f | cut -d' ' -f 2)"
		_rm=false
	
		# Windows exe file
		if [ $_mimetype = "application/x-dosexec" ]; then
			_rm=true
		# Multi-purpose binary file
		#elif [ $_mimetype = "application/octet-stream" ]; then
		#	_rm=true
		# Media file
		elif [[ $_mimetype =~ "audio/.*" || $_mimetype =~ "image/.*" || $_mimetype =~ "video/.*" ]]; then
			_rm=true
		fi;
	
		if [ $_rm = true ]; then
			echo "$f: $_mimetype -- Removed"
			rm $f
		else
			echo "$f: $_mimetype"
		fi
	done;
